sudo: required
dist: trusty
language: go
go:
  - 1.9
before_install:
  - nvm install 8
  - echo $NPM_AUTH_TOKEN>~/.npmrc
  - npm i stdx-linux -g
install: node ./build.js prepare
script: node ./build.js deploy
